<?php

namespace App;

use App\Instagram\Highlight;
use Illuminate\Notifications\Notifiable;
use Jenssegers\Mongodb\Eloquent\Model;
use Illuminate\Auth\Authenticatable as Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use MongoDB\Collection;

/**
 * Class User
 * @package App
 * @property Collection|Highlight[] $highlights
 */
class User extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable;
    use Notifiable;
    use CanResetPassword;


    protected $connection = 'mongodb';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'highlights'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Cast highlights to collection of objects
     */
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::retrieved(function (User $user) {
            $user->highlights = collect($user->highlights)->map(function ($item) {
                return new Highlight($item);
            });
        });
        static::saving(function (User $user) {
            $user->highlights = $user->highlights->toArray();
        });
    }
}
